### ISSUE TITLE
Group syllables across staves

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon#306]
Sometimes a syllable will span across 2 staff lines. For example, below the **ge** syllable starts at the end of the first line and only ends later on in the second line.

![screen shot 2018-09-26 at 2 22 02 pm](https://user-images.githubusercontent.com/19499204/46100507-8fb49880-c197-11e8-8940-313c02aab0c9.png)

Due to this, users should be able to group syllables, and possibly all sub categories, across staff lines.

**Comment by JRegimbal** [comment]
@vigliensoni the blocking part of this issue is that we don't know how to represent a syllable spanning across multiple staff lines. While the attributes `prev`/`follows` seem like they *might* be useful, it's unclear if this is the proper way to represent syllables spanning pages or staves. Even if this is true, it is unclear if it is applied to the `<syllable>`, the `<neume>`, the `<syl>`, or some combination of the three.

**Comment by JRegimbal** [comment]
I wrote two functions to convert back and forth between the `<sb>`-based way of representing multiple systems (and syllables across staves) and the `<staff>`-based way that we currently use. In the latter, split syllables across staves use `@follows` to relate the second half of the syllable to the first.

Since adding `<sb>` support to Verovio would be difficult to say the least, converting back and forth would probably be the best approach, at least for now.

**Comment by JRegimbal** [comment]
Added feature to Verovio that write `@follows` and `@precedes` as `mei:follows` and `mei:precedes` respectively to the SVG. This will let us tell which syllables are associated with each other by looking through the DOM without querying Verovio.

**Comment by JRegimbal** [comment]
> Added feature to Verovio that write `@follows` and `@precedes` as `mei:follows` and `mei:precedes` respectively to the SVG. This will let us tell which syllables are associated with each other by looking through the DOM without querying Verovio.

Added in DDMAL/verovio@021cca3995ecf62fb8a.
