### ISSUE TITLE
merging syllables causes neumes to jump

### ISSUE THREAD

**Issue by caitlin-hutnyk** [DDMAL/Neon#626]
merging syllables on first page of standard diva view on 5th stave yields syllables jumping

**Comment by JRegimbal** [comment]
It seems that the syllable that jumps starts positionally before the staff on the same system. However in the source MEI file the clef precedes the entire syllable. Applying any operation to the page (even just dragging a syllable) forces all elements in the staff to be reordered by x-position. In the new x-position based order, the syllable precedes the clef. Position is then determined by the default clef in the `staffDef`, which is a C clef one line up, resulting in the shift in rendering (fidelity of pitch not of position in MEI).

I'd argue that since the encoding of this syllable was in error in the first place (the first punctum and the C clef should form an F clef) that this doesn't need to be handled.
