### ISSUE TITLE
re-associate to nearest staff

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#636]
The function "re-associate to nearest staff" doesn't seem to work properly (if it works at all). There should be a way to take existing neumes on the page and lock them to pitches on a newly drawn, or newly extended, staff, without having to delete the neumes and re-enter them. (This would be particularly useful on early versos, e.g. 2v, where staff lines frequently need to be redrawn to compensate for their slightly curved/diagonal appearance in the photo.)

**Comment by JRegimbal** [comment]
It seems that (at least in some cases) the button to trigger reassociation doesn't have an event on it. I'll fix this and then see if the behavior is correct otherwise.

**Comment by JRegimbal** [comment]
It seems that the issue was in part that the button was appearing for elements that should not be able to be reassociated. The supported elements are syllables, clefs, and custodes (which in MEI are direct children of a layer). It now appears to be working on these three kinds of elements. Please let me know if your issue is still happening!
