### ISSUE TITLE
neumes that cross staffs

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#643]
Occasionally the automatically generated staff lines divide what should be a single neume/syllable, e.g. "-nus" at the top of 10r. Attempting to group the relevant neumes--whether by merging the two systems, or by re-drawing the neumes on an extended staff--causes a hang.

**Comment by JRegimbal** [comment]
At least in the case of 10r, this seems to be due to the neume/syllable being initially treated as a single logical syllable across different staves. This is correct, but since the expected case of these split syllables is across actually different staff lines that wouldn't be merged, they continue to be treated as linked syllables after merging. I don't experience the problem after selecting the syllables, clicking "Toggle Linked Syllables", and then grouping the neumes. Does this seem to avoid the issue for you?

**Comment by annamorphism** [comment]
I can't always seem to get that workaround to work. Sometimes "toggle linked syllables" doesn't appear, but "group neumes" still leads to a hang without doing anything.

**Comment by annamorphism** [comment]
I think updates to linked-syllables have fixed this issue.
