### ISSUE TITLE
behaviour of grouped neumes at clef changes

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#650]
Occasionally, a clef change will occur inside a syllable containing multiple neumes. When this happens, the resulting neumes have some very odd behaviour. 
Here, for example, the green distropha has the pitch names as if belonging to C3 (the previous clef on the line) but is rendered as if dominated by the C2 that follows 
![image](https://user-images.githubusercontent.com/67451875/106473101-61cf7500-6471-11eb-890c-55519f55bd7c.png)

Attempting to replicate this with inserted clefs rather than pre-existing ones gives slightly different behaviour. Here, after being "grouped" on either side of a C4, the neumes are re-pitched as if they all belonged to the C4 clef, but then rendered as if they belonged to their original C1 clef (!) 
![image](https://user-images.githubusercontent.com/67451875/106473542-e15d4400-6471-11eb-8777-a761a2939bc8.png)

Finally, if one undoes this grouping--leaving the inserted clef--and redoes it, the neumes render in their original location, but now labelled as if belonging to the first (C1) clef.
![image](https://user-images.githubusercontent.com/67451875/106473865-4add5280-6472-11eb-9093-04dda6694df1.png)

**Comment by annamorphism** [comment]
here's that same distropha on 37r line 6, ungrouped from the neume that follows and rendered correctly: 
![image](https://user-images.githubusercontent.com/67451875/106474679-28980480-6473-11eb-988e-c41dac6f1cdf.png)
And here it is grouped with its neighbour, now labeled as for the second clef but rendered as for the first:
![image](https://user-images.githubusercontent.com/67451875/106474807-45ccd300-6473-11eb-8bb9-9b5c103a582e.png) 

And here an undo and second grouping has left them in the correct places, labelled as though for the first clef:
![image](https://user-images.githubusercontent.com/67451875/106475129-993f2100-6473-11eb-9412-22c98ed29ba9.png)

**Comment by JoyfulGen** [comment]
I can confirm that when there's a clef change in the middle of a long syllable, once you get the neumes to behave Neon ignores the second clef and labels all the notes based on the first clef. I can find no way to fix this; if I want the syllable to stay whole, the second clef will be ignored.

An illustration (same situation as @annamorphism's): the pitches of the pes that my cursor is hovering over are identified as E and G, which is what they are relative to the first clef on the line, but the new clef should be making them G and B.
<img width="1358" alt="Syllable ignores clef change" src="https://user-images.githubusercontent.com/83373378/152832341-099191df-5102-474c-90e8-aced64317033.png">

This issue is a low priority, because a clef change in the middle of a syllable is a pretty rare phenomenon. However, the fact that it doesn't have any solution is more problematic.

**Comment by annamorphism** [comment]
I think there was verbal discussion around this issue when I encountered it, and the problem is that syllables must remain unbroken (similar to the issue of syllables broken by a new staff). 
That suggests the the solution could be similar, i.e creating a "linked" syllable over a clef change. Right now you can only link syllables with a staff break between them, but if the trigger were instead the appearance of a clef, it would also cover these cases.

**Comment by JoyfulGen** [comment]
After further discussion, @annamorphism and I can suggest two possible fixes for this:

1. Adding a button that can allow the user to insert a clef into the nearest syllable, like we already can for divisios. Clefs affect pitch though, so we don't know if this would work. @yinanazhou, what do you think?
2. If 1. doesn't work, another option would be to add a toggling function across clefs. So if the user selects syllables on either side of a clef, the option appears to link them, just as it does for syllables that cross staves.
