### ISSUE TITLE
absent bounding boxes

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#656]
it is possible to make neumes appear apparently without any bounding boxes for their texts (see pe-des, Salzinnes 83r, line 2). Some "boxless" neumes receive boxes when their syllables are given a text, but  if the neumes are first merged with those around them, the result has no bounding boxes.
Pedes, with a text box for pe- and an empty syllable (and no text box) for -des:
![image](https://user-images.githubusercontent.com/67451875/108881103-f80a3d00-75d0-11eb-96ea-092e65c85f8b.png)
Grouped neumes: box for "pe" has now disappeared.
![image](https://user-images.githubusercontent.com/67451875/108881348-343d9d80-75d1-11eb-8aca-12c8cc8a5a58.png)
text added: still no bbox
![image](https://user-images.githubusercontent.com/67451875/108880598-731f2380-75d0-11eb-859a-9f906301bd99.png)

**Comment by annamorphism** [comment]
note that if a text is provided for the neumes before grouping, a box appears:
![image](https://user-images.githubusercontent.com/67451875/108881807-b9c14d80-75d1-11eb-892f-5fd038aad766.png)

this box may or may not remain after the neumes are grouped.

**Comment by JRegimbal** [comment]
RE: -des, there actually is a bounding box but it is located on the second-to-last staff line of the page. This seems to be a fun quirk of OMR. For the disappearing bounding box, the width of the merged box is set to -18. I'll have to check, but it seems like since by default the neumes to the left have a bounding box to the right of the right neumes' bounding box a negative number is entered when really we should be taking the absolute value.

**Comment by annamorphism** [comment]
> RE: -des, there actually is a bounding box but it is located on the second-to-last staff line of the page. 
So there is! It had also disappeared due to the bug above. N.b. though it reappears  if one "undoes" the grouping, the bounding boxes that made it disappear in the first place stay disappeared.

**Comment by JoyfulGen** [comment]
This issue is still appearing; bounding boxes for merged syllables sometimes disappear (working on Salzinnes folio 002r). There is also, in folio 002v, a syllable that never had a bounding box in the first place (in the hot pink rectangle):
![folio 002v neon w: image](https://user-images.githubusercontent.com/83373378/117662397-82dceb80-b16d-11eb-8904-c6a76adf1e46.png)

Though we know the BB should be somewhere on the page, it is very hard to find. Even when sliding the image opacity to zero, we just can't see it. 
![folio 002v neon no image](https://user-images.githubusercontent.com/83373378/117662588-b9b30180-b16d-11eb-9666-53a73ed5e933.png)

It would perhaps be useful for the highlighter to be a starker colour. At the moment, hovering over a syllable makes it red, but that red can get lost in the pink and oranges.

**Comment by martha-thomae** [comment]
Might this be coming from the Text Alignment job, @timothydereuse ?

**Comment by JoyfulGen** [comment]
We've made a discovery which is relevant to this problem. It turns out that a BB can be "flipped" by dragging one of its borders over the other. When we do that, the dotted outline of the BB remains, but its colour disappears:
<img width="168" alt="Screen Shot 2021-05-17 at 11 25 26 AM" src="https://user-images.githubusercontent.com/83373378/118517294-16ca2c80-b705-11eb-87b9-6f606c7befe2.png">
If we click elsewhere, the dotted outline disappears too and it looks like the BB is gone. But if we click and drag over the region where we know it's hiding, the dotted outline reappears and we can then "flip" the BB back:
<img width="159" alt="Screen Shot 2021-05-17 at 11 25 35 AM" src="https://user-images.githubusercontent.com/83373378/118517545-4c6f1580-b705-11eb-8ed9-ab033c9da11b.png">
When a syllable appears to not have a BB, or when two merged syllables lose their BB, this is usually the problem. Using the click and drag feature usually allows us to find the invisible BB and flip it back to make it visible again. So the useful fix would be make it so that flipped BBs remain coloured.

**Comment by martha-thomae** [comment]
@JoyfulGen: Awesome discovery! thanks for updating :)
We also need to see if the `@ulx`,` @uly`, `@lrx` and `@lry` coordinates in the MEI file are affected by this.

By the way, does it gives you any validation issues if the BB is flipped (so, when it doesn't show)?
could you check the `@ulx`,` @uly`, `@lrx` and `@lry` coordinates when you have a flipped box and share them here?

**Comment by annamorphism** [comment]
@martha-thomae Both the visible and "invisible" bounding boxes give valid MEI files. 

I tried this in browser Neon and the same thing applies. 
Here are the coordinates for one such "flipped" box, on folio 001r:   <zone xml:id="m-7f45ab84-89b2-495d-bf5c-9e0a155be985" ulx="2690" uly="1203" lrx="2776" lry="1364"/> 

and the same after a "flip" <zone xml:id="m-7f45ab84-89b2-495d-bf5c-9e0a155be985" ulx="2690" uly="1203" lrx="2544" lry="1364"/> where the lrx is now smaller than the ulx.

**Comment by annamorphism** [comment]
n.b. I don't seem to get a result from clicking in the region of the "invisible" box though (in either Rodan-Neon or browser-Neon.) The box is just gone.

**Comment by martha-thomae** [comment]
> n.b. I don't seem to get a result from clicking in the region of the "invisible" box though (in either Rodan-Neon or browser-Neon.) The box is just gone.

I think you should click and **drag**, from what I understood.

**Comment by martha-thomae** [comment]
> @martha-thomae Both the visible and "invisible" bounding boxes give valid MEI files.

Thanks for looking into this, @annamorphism!

I checked based on your feedback and it seems that the only case in which the coordinate values can be invalid is when they are negative. (They only accept non-negative data values according to the [documentation](https://music-encoding.org/guidelines/v4/attribute-classes/att.coordinated.html)). That is why the file is still valid, thanks!

> I tried this in browser Neon and the same thing applies.
> Here are the coordinates for one such "flipped" box, on folio 001r: `<zone xml:id="m-7f45ab84-89b2-495d-bf5c-9e0a155be985" ulx="2690" uly="1203" lrx="2776" lry="1364"/> `
> 
> and the same after a "flip" `<zone xml:id="m-7f45ab84-89b2-495d-bf5c-9e0a155be985" ulx="2690" uly="1203" lrx="2544" lry="1364"/>` where the lrx is now smaller than the ulx.

There is something really weird here, and this has nothing to do with the original issue of flipping things. Let me know if you agree:

So, `ul` means upper-left corner, and then `ulx` is upper-left x coordinate and `uly` is upper-left y coordinate. Similarly, `lr` means lower-right corner, so `lrx` is the lower-right x coordinate and `lry` is the lower-right y coordinate. I would think that because the lower-right (`lr`) corner is both to the right and lower than the upper-left (`ul`) corner, that the `lrx` value should be greater than the `ulx`, and the `lry` value should be smaller than the `uly` value. However, in both cases `lry` is always greater than `uly` (regardless of the bbox being flipped or not).

I feel like the coordinates were encoded wrong, does anybody else agree?

So, `uly` and `lry` are inverted (from what they are supposed to be) in all cases. And `ulx` and `lrx` are inverted only when the box is flipped (second example Anna sent). 

They should always be:

- `lry < uly` (**lower** y < **upper** y)
- `lrx >  ulx` (**right** x > **left** x)

**Comment by martha-thomae** [comment]
> I tried this in browser Neon and the same thing applies.
> Here are the coordinates for one such "flipped" box, on folio 001r: `<zone xml:id="m-7f45ab84-89b2-495d-bf5c-9e0a155be985" ulx="2690" uly="1203" lrx="2776" lry="1364"/> `
> 
> and the same after a "flip" `<zone xml:id="m-7f45ab84-89b2-495d-bf5c-9e0a155be985" ulx="2690" uly="1203" lrx="2544" lry="1364"/>` where the lrx is now smaller than the ulx.

There is something really weird here, and this has nothing to do with the original issue of flipping things. Let me know if you agree:

So, `ul` means upper-left corner, and then `ulx` is upper-left x coordinate and `uly` is upper-left y coordinate. Similarly, `lr` means lower-right corner, so `lrx` is the lower-right x coordinate and `lry` is the lower-right y coordinate. I would think that because the lower-right (`lr`) corner is both to the right and lower than the upper-left (`ul`) corner, that the `lrx` value should be greater than the `ulx`, and the `lry` value should be smaller than the `uly` value. However, in both cases `lry` is always greater than `uly` (regardless of the bbox being flipped or not).

I feel like the coordinates were encoded wrong for the `y` values, does anybody else agree?

So, `uly` and `lry` are inverted from what they are supposed to be. (And `ulx` and `lrx` are inverted only when the box is flipped—second example Anna sent.) 

They correct values would adhere to:

- `lry < uly` (**lower** y < **upper** y)
- `lrx >  ulx` (**right** x > **left** x)

But it seems like Neon is encoding bboxes with the higher values for `x` and `y` in the `lr` corner when the box is shown. I will raise a separate issue for this.

Thanks, Anna!

**Comment by martha-thomae** [comment]
So, for the current issue (the absent bounding boxes), maybe the bounding boxes not being shown (in the flipped version) could have to do with what Anna is saying about `lrx` being smaller than `ulx`. Maybe the logic behind Neon doesn't render things when these values are inverted(?)

>and the same after a "flip" <zone xml:id="m-7f45ab84-89b2-495d-bf5c-9e0a155be985" ulx="2690" uly="1203" lrx="2544" lry="1364"/> where the lrx is now smaller than the ulx.

**Comment by JoyfulGen** [comment]
I believe this issue was fixed here https://github.com/DDMAL/Neon/issues/749. I haven't encountered it again since, so I'm closing it.
