### ISSUE TITLE
Request: Keystroke Shortcuts

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/Neon#665]
-  [x] for each insert option
-  [x] switch between edit and insert mode
-  [x] delete
-  [x] different edit options
-  [x] Switch between different highlight options
-  [x] Grouping and ungrouping
-  [x] Arrow keys for bounding boxes
-  [x] Edit syl text when pressing enter after selecting a bbox
- [x] Add all these hotkeys to the hotkey menu

**Comment by JRegimbal** [comment]
Many of these already exist actually! Check the hotkeys menu under the dropdown in Neon.

**Comment by thesoundbyle** [comment]
> Many of these already exist actually! Check the hotkeys menu under the dropdown in Neon.

Oh I just found them!
I'll make of the ones that are listed in Neon

Small note: It would be nice when selecting a symbol in the edit function, it would switch to edit mode.

**Comment by carrieeex** [comment]
@thesoundbyle I think there is a hotkey for deleting something. In a PC it's Control+D or backspace.

**Comment by carrieeex** [comment]
It would be nice if we can use arrow keys (left and right) to switch between different bounding boxes. For example, when users choose "select by BBox", and then click one of the bounding boxes, press the right arrow key would switch to the BBox on the right.

**Comment by JoyfulGen** [comment]
It would also be nice to have a shortcut for grouping and ungrouping neumes. For example, when users select certain neume components, "g" groups them and "shift g" ungroups them.

**Comment by JoyfulGen** [comment]
Tested the hotkeys for switching highlight modes and the arrow key to move between bboxes and they work perfectly!

**Comment by JoyfulGen** [comment]
Tested the enter key shortcut and it works! Extremely awesome. I do have a little request to make it even more awesome though: could you make it so that when I'm done entering the text, the bbox stays selected? That would allow the user to continue working from that point using the arrow keys, without having to click on a bbox at all.

**Comment by jinh0** [comment]
> could you make it so that when I'm done entering the text, the bbox stays selected?
Definitely! I don't know why it isn't like this in the first place. If you edit the text as before without the use of this enter key, it'd still unselect the bbox you were on. Therefore, this will require its own fix outside of just the enter key shortcut... I'll make a new issue about this and try fixing it.

**Comment by jinh0** [comment]
@JoyfulGen How does this look?

https://user-images.githubusercontent.com/40512164/168674839-25467e7c-4d71-4e90-be15-fff35adc720b.mov

**Comment by JoyfulGen** [comment]
@jinh0 both of these look good to me. I like that if you edit a syllable through the text box, that's the syllable that's selected afterwards. Thank you!

**Comment by annamorphism** [comment]
> Right now, I've made it so that it selects the syllable just edited, ignoring any previous selection.
> 
>  Screen.Recording.2022-05-16.at.4.17.20.PM.mov
I find this video a bit confusing, because both "lem" and "cun" are highlighted on the page, just "lem" (="something") is highlighted in the text, but the editing action is on "cun". So if you were trying to remember what it was you were putting into the text box, what's highlighted is confusing.

**Comment by JoyfulGen** [comment]
Tested the "g" toggle for grouping and ungrouping and it's AWESOME. I can go SO FAST. Everything seems to work smoothly for grouping/ungrouping neumes and staves. 

The behaviour with toggled syllables is a bit strange, however. Normally, when selecting a syllable that's toggled with the next one on the staff, the user only gets the option to "Toggle Linked Syllables." Once the syllables are untoggled, selecting one of them gives the option to "Merge" or "Ungroup", as usual. The issue here is that the "g" shortcut allows the user to avoid the "Toggle Linked Syllables" entirely and attempt to ungroup linked syllables. This results in the neume(s) of the second half of the linked syllable to be duplicated on the staff above. This duplicate has the same neume ID, which makes the file invalid and Neon loses its mind. The original second syllable and its duplicate are also toggled with each other. 

Here's the MEI of the first syllable (the duplicate):

<img width="826" alt="253v duplicate" src="https://user-images.githubusercontent.com/83373378/169530435-fdc8da94-1d80-4a20-80b2-3d63e411a2ec.png">

And here's the MEI of the second syllable:

<img width="819" alt="253v OG" src="https://user-images.githubusercontent.com/83373378/169530444-1e559f4f-ff65-4d2b-82d9-e2f68e1bc1bb.png">

I think the ideal solution here is that if the user attempts to ungroup a toggled syllable, the syllables automatically untoggle themselves.

This is the entire MEI file
[253v tfw you're toggled with your clone.mei.zip](https://github.com/DDMAL/Neon/files/8740236/253v.tfw.you.re.toggled.with.your.clone.mei.zip)
