### ISSUE TITLE
Unable to ungroup syllables

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon#675]
When we were correcting in Neon, we found that **sometimes** many syllables are classified as one syllable.....And we cannot ungroup or delete the syllable. We have to delete all the misclassified neumes and reclassify them.

**Comment by JoyfulGen** [comment]
This happened again in folio 040v: 
<img width="668" alt="Many neumes one syllable 040v" src="https://user-images.githubusercontent.com/83373378/119019143-df5cb980-b96a-11eb-8f71-fbd37a219499.png">
This is the MEI file: 
[Neon 040v all in one syllable.mei.zip](https://github.com/DDMAL/Neon/files/6517601/Neon.040v.all.in.one.syllable.mei.zip)
It's generally possible to fix the problem by ungrouping the syllable, but entering all the new ones and adjusting the bounding boxes is time-consuming.

**Comment by martha-thomae** [comment]
Since this is not an issue in Neon (one can actually ungroup syllables and regroup them at will), we will close this issue. In its place, we will raise two other issues: one for improving the initial grouping of syllables in the Text Alignment job and another to improve the documentation of Neon itself to clarify the steps involved in ungrouping and grouping actions so that the users don't waste their time figuring this out.

Thanks @yinanazhou and @JoyfulGen for reporting on this, we definitely need to improve the documentation and maybe we can also improve the syllable groupings from the start. I will appreciate your help raising these other two issues. Thank you!

**Comment by yinanazhou** [comment]
The issue happens in the many-to-one syllable in 021r. For the first misclassified syllable, I cannot ungroup syllable/neume/neume component. I took several screenshots and saved the mei file.
![image](https://user-images.githubusercontent.com/74484576/119167732-ba636600-ba92-11eb-90b3-efd6d28ab8d6.png)
![image](https://user-images.githubusercontent.com/74484576/119167754-c2230a80-ba92-11eb-9b2d-fde51e487170.png)
![image](https://user-images.githubusercontent.com/74484576/119167765-c51dfb00-ba92-11eb-8517-8cceea74fa99.png)
[issue675.zip](https://github.com/DDMAL/Neon/files/6523834/issue675.zip)

**Comment by martha-thomae** [comment]
Thanks for the clarification, @yihongluo! Yes, this is a big issue. Thanks for including the screenshot for illustrating it.

**Comment by annamorphism** [comment]
The issue on 21r is connected to a linking syllable ("lum" on the line above) and may be related to #647 , but it is not exactly the same issue. It is possible the same fix (fixed in-browser (1c34e14)) will work, but maybe not; I haven't yet replicated the issue one way or the other.

**Comment by kemalkongar** [comment]
Tested locally, closing unless it reappears when changes are pushed to Rodan.
