### ISSUE TITLE
Request to add a left tail to a neume

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon#701]
Hi, I am trying to add a left tail to a neume in Neon. I'm thinking about first adding a primitive element, and then adding a head shape (as illustrated in the screenshot). @annamorphism, what would a musicologist like to use? Thank you for your help!

![image](https://user-images.githubusercontent.com/74484576/129571368-9a9232be-dab1-4d1e-b171-878f5e6da6eb.png)

**Comment by annamorphism** [comment]
Hmm. Neumes with left tails never appear by themselves, so they aren't _exactly_ a "primitive element". That's definitely the easiest place to find them, though, so probably a good place to implement it.   I think they make the most sense under the "head shape" menu, but then the name of the menu should probably be changed (maybe to "change note appearance" or something). Otherwise nobody is going to find the option.

**Comment by martha-thomae** [comment]
Hello everyone! 
Here I am summarizing the discussion we had with @GabbyHalpin and @yinanazhou :

So, after discussing this with an expert in neumes and in MEI (Elsa De Luca), she indicated that the down tail on the right and on the left of a neume is actually encoded in the same way with a `<nc>` that has an attribute of `@tilt=s` (south, for the tail going down).

- So, a virga would be encoded as `<nc tilt="s">`
- And a (let's call it for now) "reversed virga" would be encoded exactly the same `<nc tilt="s">`

There is no difference in the encoding of the neume component. However, **we might be able to use the placement of the `<nc>` within `<neume>` to determine whether the tail goes in the right or in the left**. See the following two examples:

- If we have a neume that **starts** with the component (`nc`) that includes the attribute `@tilt=s`, this one has the tail on the left side.
```xml
<neume>
  <nc tilt="s" pname="d" oct="3"/>
  <nc pname="c" oct="3"/>
</neume>
```

- And, on the other hand, if we have a neume that **ends** with the component (`nc`) that includes the attribute `@tilt=s`, this one has the tail on the right side.
```xml
<neume>
  <nc pname="c" oct="3"/>
  <nc tilt="s" pname="d" oct="3"/>
</neume>
```

So, at least for now, rather than adding this as a primitive, let's just render the stem differently based on the position of the neume component with the downward tail.

**Comment by carrieeex** [comment]
As mentioned [here ](https://github.com/DDMAL/Neon/issues/703#issuecomment-905510699)that "revised virga" is working properly in Neon in Rodan-staging! Now the drop-down menu needs to be updated:
![image](https://user-images.githubusercontent.com/59303880/130801713-9546bb64-6712-4fa3-a75b-00a129b3cddc.png)
it should contain all the styles (add "reversed virga" to the list) so the user can replace the neume component without deleting or breaking the syllable.

**Comment by carrieeex** [comment]
and for now, if the user selects "virga" in the list, it appears to be a "reversed virga":
![image](https://user-images.githubusercontent.com/59303880/130802603-cb4bd2ac-41fc-418b-a0d7-d6644c9428e3.png)
![image](https://user-images.githubusercontent.com/59303880/130802631-0cdccf8f-a50f-4849-9d5d-7afe4bbaf7e5.png)
which needs to be fixed.

**Comment by GabbyHalpin** [comment]
My bad clicked the wrong button. However, is this issue now resolved? @martha-thomae

**Comment by JoyfulGen** [comment]
Update: the reversed virga has been tested in browser Neon and it works perfectly.

**Comment by JoyfulGen** [comment]
The reversed virga works on rodan_staging too! Closing issue now.
