### ISSUE TITLE
neume components of the torculus overlap

### ISSUE THREAD

**Issue by carrieeex** [DDMAL/Neon#706]
The three neume components (punctum) of the torculus overlap with each other, like in Salzinnes folio 060v below:
<img width="446" alt="060v torculus neumes overlap" src="https://user-images.githubusercontent.com/59303880/120323574-358d0d80-c318-11eb-9b1e-3cb4ed741777.png">

**Comment by JoyfulGen** [comment]
After discussing this further, @martha-thomae suspects that the problem could be a bounding box issue. In Salzinnes, the torculus was the only neume with multiple puncta classified together as one neume. All other neumes, such as the podatus, were split into individual puncta. It's therefore possible that in the case of the torculus, all three puncta were encoded as being part of the same zone and Neon didn't know where to put them in relation to each other. 

If this theory is correct, it could become a much larger problem when encoding and correcting the Einsiedeln manuscript. In this case, I'm training the IC to recognize all podatus, clivis, and torculus categories as entire neumes, so presumably this zone issue would occur in every one of these (except perhaps the podatus, since the puncta in a podatus are supposed to be one on top of the other anyway). 

A possible solution would be to make a general rule, such as "if all neume components are part of the same zone, put them next to each other, starting from the first neume component in the code." This would work for both the clivis and the torculus. However, once again the podatus is a problem, because putting the puncta next to each other would be wrong. Another podatus issue is that the musical spelling of a stepwise podatus isn't consistent between manuscripts:

Here is a stepwise podatus in Salzinnes: 
<img width="74" alt="Screen Shot 2021-08-25 at 9 33 07 AM" src="https://user-images.githubusercontent.com/83373378/130800083-efef3022-8927-43d7-a262-343a816f98f9.png">

And here's one in Einsiedeln:
<img width="57" alt="Screen Shot 2021-08-25 at 9 33 41 AM" src="https://user-images.githubusercontent.com/83373378/130800101-c47da422-db95-4b6c-b0d0-9bd5bbad7678.png">

**Comment by JoyfulGen** [comment]
I've confirmed that the zone issue occurs with every clivis and scandicus in Einsiedeln, as well as with every torculus as before. For example, a clivis that looks like this:
<img width="83" alt="002r OG clivis" src="https://user-images.githubusercontent.com/83373378/133434635-a7c9d955-fbf1-4741-81e9-d1cd4c57cc6c.png">
Shows up like this:
<img width="72" alt="002r Clivis misaligned" src="https://user-images.githubusercontent.com/83373378/133434308-f0d5a5a6-b7cf-46f9-af55-7211e3589e9a.png">
And a scandicus that looks like this:
<img width="124" alt="002r OG scandicus" src="https://user-images.githubusercontent.com/83373378/133434364-42686333-7453-4cd1-bd6d-834b455fa1a5.png">
Shows up like this:
<img width="121" alt="002r scandicus misaligned" src="https://user-images.githubusercontent.com/83373378/133434410-af210d7d-f894-455e-be95-cae17bb6fd6a.png">
