### ISSUE TITLE
Support for divisio

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Neon#709]
One last thing we need support for in Neon that we have already found several times in the manuscripts we have worked on so far is the encoding of divisio. Divisio is a barline that is found between different chants (or the ending part of the chant, the "euoae"). Here you can see an example of divisios:

![Screen Shot 2021-08-27 at 9 01 44 PM](https://user-images.githubusercontent.com/13948831/131201337-1a0442a3-d06f-4f6e-85f1-d46d1f9a9be0.png)

Although there is no support for it in the current version of MEI ([version 4.0.1](https://music-encoding.org/guidelines/v4/content/#)), there will be support for it in the next MEI version ([5.0.0-dev](https://music-encoding.org/guidelines/dev/content/index.html)). The element for encoding these "divisio" lines will be `<divLine>` (you can find information of it in [5.0.0-dev](https://music-encoding.org/guidelines/dev/content/index.html) by going to elements and searching for `<divLine>`—direct link [here](https://music-encoding.org/guidelines/dev/elements/divLine.html)).

**Comment by martha-thomae** [comment]
A few notes:

We will need to move to the **5.0.0-dev** version for this change. Based on the XML processing instructions (see below) and the root mei element of a file exported from Neon, the current schema of MEI we are using is: `https://music-encoding.org/schema/4.0.0/mei-all.rng`

XML processing instructions:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

MEI root element of the same file:
```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
```

We will need to change lines 2 and 3 `@href` value for `https://music-encoding.org/schema/dev/mei-all.rng` and the root element `@meiversion` value for `5.0.0-dev` so that we use the version of MEI where the `<divLine>` element is valid.

**Comment by martha-thomae** [comment]
And a second note:

I just noticed that [`<divLine>`](https://music-encoding.org/guidelines/dev/elements/divLine.html) doesn't have any parent element in the schema (see the "contained by" section, it is empty). I think this is a mistake in the schema. The parent should be `<layer>`. So, we need to modify the MEI schema for allowing `<divLine>` to be a child of `<layer>`. Maybe @yinanazhou or @carrieeex can look into this part involving modifying the MEI schema.

My guess is that this is happening because `<divLine>` isn't a member of any model class (see the "Declaration" section, there is no "model class" in the `<classes>` listed). Compare this to the element [`<barLine>`](https://music-encoding.org/guidelines/dev/elements/barLine.html) for example (it contains a `<memberOf key="model.eventLike"/>` within its `<classes>`). When changing the schema for `divLine`, I would use `barLine` as reference.

**Comment by carrieeex** [comment]
A short note:
For the current version (MEI 4.0.0), if we add the ` <divLine> ` in the interactive classifier, the ` MEI_encoding ` job of the OMR workflow will generate it in the MEI file (see code below from Einsiedeln folio 004r); and when we import this MEI into Neon, the `MEI Status` will remain "Checking..." (I thought it was because it does not support `<divLine>` yet). If we edit it in Neon, the ` <divLine> ` will disappear in the MEI as Neon auto-generates a new one; while the MEI status remains "checking" (and I'm not sure why).

(Thanks to @JoyfulGen for explanations and files)

```
<divLine xml:id="m-b85cd7e7-3bb2-45ca-a069-22e6572fded8" facs="#m-3ce0fa81-3922-436a-a028-6194677a38c4" />
```
[004r.zip](https://github.com/DDMAL/Neon/files/7226561/004r.zip)

[Einsiedeln__Stiftsbibliothek__Codex_611_004r.zip](https://github.com/DDMAL/Neon/files/7226562/Einsiedeln__Stiftsbibliothek__Codex_611_004r.zip)

**Comment by GabbyHalpin** [comment]
![Screen Shot 2021-09-25 at 2 26 42 PM](https://user-images.githubusercontent.com/68965715/134782510-8c70e65f-0db7-4e38-931d-0727a34d7f1c.png)

For the desired division, these are some of the options supported by SMuFL, there may be others as well. Just for clarity, which kind are we looking for, since there are different heights, etc.

**Comment by carrieeex** [comment]
and for convenience and future reference, the support for divLine in MEI schema is discussed [here](https://github.com/music-encoding/music-encoding/issues/861).

**Comment by JoyfulGen** [comment]
Update: the divisio maxima has been implemented in Neon browser and it works perfectly.

**Comment by JoyfulGen** [comment]
Summarized what's left in this new issue https://github.com/DDMAL/Neon/issues/856, so closing this one now.
