### ISSUE TITLE
Request for error message when trying to make a ligature out of something other than two puncta

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#777]
In Neon, the `toggle ligature` function only works if the two selected glyphs are puncta. This is fine and great! 
It follows that if you accidentally try to toggle, say, a reversed virga with a punctum, it won't work and nothing will happen. However, a message will appear in the top-left corner saying that the ligature has been toggled. This is slightly confusing. It would be easier to figure out the mistake, I think, if the message said the toggling had failed.

<img width="1191" alt="Ligature not, in fact, toggled 272v" src="https://user-images.githubusercontent.com/83373378/157080607-32f54722-b7da-4e06-98da-22c1f5c771b0.png">

This is a super non-urgent issue, because it's just a little user-friendliness enhancement.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen , I've pushed the changes for this issue. Could you please test it? Thanks for pointing out this issue!

**Comment by annamorphism** [comment]
alternatively, it wouldn't be a bad thing to allow reverse puncta to be in a ligature...

**Comment by yinanazhou** [comment]
@annamorphism , I've tried it, but it looks weird in Neon. What about automatically changing reverse puncta to puncta when toggling ligature? This will delete `@tilt`, and add `@ligated`. I can also do this for licquescents. 

> alternatively, it wouldn't be a bad thing to allow reverse puncta to be in a ligature...

**Comment by yinanazhou** [comment]
> nvm I see @yinanazhou is quicker than me!
> 
> Right now I'm getting a failed message if I do a reverse-virga and a punctum, but I get a successful ligature for two inclinatums or two virga, and I don't get the option at all if one of them is a liquescent. This seems inconsistent.

Oops, my bad. I will work on this tomorrow! Just to make sure, what kind of `nc` should be successfully ligated, and what should not? Do we need the `toggle ligature` option for any combinations of two `nc`s?

**Comment by annamorphism** [comment]
@yinanazhou I like that solution. So any two adjacent descending neumes (of any shape) could have "toggle ligature", and then they would turn into a punctum with ligated=yes in the file, correct?
We don't NEED every combination to be a ligature (the user can always change things to be a punctum themselves, after all.) But I don't think it would be a bad thing either.  And reverse-virga + punctum would be a very nice option to be able to put a ligature in, because it is sort of the underlying shape of the neumes.

**Comment by annamorphism** [comment]
basically we want one of the following things:
1) If user selects two puncta, they can "toggle ligature" and it works; nothing else gives this option.  [[this is the original I think, when there were fewer note shapes]]
OR
2) If user selects two (adjacent) ncs, they can press "toggle ligature" but it only works if they are puncta; otherwise it returns a "ligature failed" and the neumes stay put. [[the option suggested by @JoyfulGen]]
OR
3) If user selects two adjacent ncs of any shape, they can toggle ligature, and these neumes always turn into two puncta with ligature; "ligature failed" is reserved for other issues, like choosing ncs that aren't adjacent.

My personal preference is option (3) but any one of them could work I think.

**Comment by yinanazhou** [comment]
Hi @annamorphism and @JoyfulGen , I've implemented option (3). It turns out frontend Neon could not successfully distinguish the shapes of ligature, virga, or inclinatum. Therefore, I moved the `isLigature` check to verovio. Issue #641 should also be fixed by now. Please let me know if anything unexpected happened.

**Comment by JoyfulGen** [comment]
I tested the fix, it works very well. I couldn't find any strange behaviours! Closing the issue now.
