### ISSUE TITLE
New Landing Page and Dashboard Issues

### ISSUE THREAD

**Issue by chetbae** [DDMAL/Neon#833]
Issues: 

1. [x] Deleting multiple folios is broken.
2. [x] The filename that appears in the top left of editor does not accurately reflect the folio.

Wanted Features:

1. [x] Add cypress tests. - In progress
2. [x] Add option to open folios with double-click.
3. [x] Shift-click should select all the files between the first one you selected and the one you're clicking on, and command-click should only select the file you're clicking on.
4. [x] Unselect files by clicking away.

**Comment by JoyfulGen** [comment]
@chetbae this looks amazing! I particularly like being able to upload different file types and then pair them. That's very neat and time-efficient. I tested all the functionalities you listed above and everything works perfectly, with the small exception of the delete function. I can delete one file at a time, but if I select more than one file and try to delete them, nothing happens.

I also have a few questions/suggestions to make the user experience even smoother:
- Would it be possible to make it so that double-clicking on a file box opens that file? I feel like that's pretty intuitive, and then there would be two ways to open a file.
- Would is also be possible to distinguish between shift-click and command-click when selecting multiple files? Shift-click selects all the files between the first one you selected and the one you're clicking on, and command-click only selects the file you're clicking on.
- At the moment, the only way to unselect a file is to click on it again. Could it be possible to unselect files by clicking away, on the background of the page? That would make unselecting multiple files much easier.
- This is really just aesthetic, but the sizes of the "boxes" for each file aren't quite consistent, so the rows don't always match up (see below). I guess longer file names could be compressed more so that the width always matches, but honestly, if you don't really care, then neither do I.
<img width="1139" alt="Boxe sizes different" src="https://user-images.githubusercontent.com/83373378/182158202-8221c5de-a0dc-4de3-be34-be5ce6692ddf.png">

**Comment by annamorphism** [comment]
this functionality is AMAZING! I can upload so many things! I can open them all at the same time (if I remember to disable my pop-up blocker anyway)! SO MUCH TIME SAVED I love it. 
however something a little weird is going on with the names: 
this is supposedly 1r (it isn't):
![image](https://user-images.githubusercontent.com/67451875/182185046-cd080191-b5e2-4de8-ba0d-ce51ef553dc3.png)

and so is this: 
![image](https://user-images.githubusercontent.com/67451875/182185100-3d37861f-71ac-4a62-a147-abab3d590fe0.png)
and this...
![image](https://user-images.githubusercontent.com/67451875/182185138-479339b2-94cc-45b1-b7bc-76ebcdbadfa7.png)

I only uploaded one file called 1r! But when I open multiple files at once several seem to be named 1r. 

I also got some sort of error about file updates that I will try to replicate in case it is relevant to this issue.

**Comment by cadagong** [comment]
> * At the moment, the only way to unselect a file is to click on it again. Could it be possible to unselect files by clicking away, on the background of the page? That would make unselecting multiple files much easier.
> 

Just wanted to mention that you can also unselect a selection by pressing "Escape". But clicking away is definitely an option that we should add!

**Comment by annamorphism** [comment]
@JoyfulGen weirdly, though I have the same different-sized button issue as you do (I think they're sort of attractively in their many shapes):
![image](https://user-images.githubusercontent.com/67451875/182196520-feda33d7-b5b8-4074-b740-a3518c46dd29.png)

I also have plenty of uploads where the file name is compressed in such a way that I can't tell what page they are at all:
![image](https://user-images.githubusercontent.com/67451875/182196838-0ef977d9-ad7d-4418-a00f-f9fcd1e01d55.png)


(Makes me wonder if we should have an option to rename during or after upload)

**Comment by chetbae** [comment]
I'm in favour of the asymmetry 🤠

**Comment by annamorphism** [comment]
update: actually the MEI file name for those (very old) uploads seems to have gotten garbled; the page is trying to load CDN-Hsmu_M2149.mei for all of them and not succeeding. Probably ok, since I can reupload those guys if I need to, but I don't know *why* its happening. 

@JoyfulGen did you have any difficulty with your old Salzinnes uploads not loading? or do you not have them anymore?

**Comment by annamorphism** [comment]
same problem for some other file names. They've gotten shortened to fit on the landing page, but it looks like the shortened name is also what it's trying to open (e.g. "cdn-hsmu-m2...leted_clef.mei")

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, could you please help confirm that this issue can be closed?

**Comment by JoyfulGen** [comment]
Yes, everything has been working smoothly for me! Closing issue now.
