### ISSUE TITLE
Pending feature request: add left/right most in-syllable divLine position check while uploading and MEI actions to move them out

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon#860]
As requested by @JoyfulGen, if the OMR process cannot eliminate left/right most in-syllable divLines, we can add a check when uploading mei files that can notify the user we have these divLines, and also provide an MEI action to move these divLines out.

**Comment by yinanazhou** [comment]
Needs @sabrina0822's confirmation on divLine encoding in the MEI-encoding job in Rodan.

**Comment by sabrina0822** [comment]
Was able to fix this in MEI-encoding job, getting ready to submit pull request today!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, since we can check this in the MEI-encoding job, could you please confirm that this issue can be closed?

**Comment by JoyfulGen** [comment]
I'd like to test the MEI_encoding job before closing the issue, but I've waiting for text_alignment to be back up. Now I think of it though, I can just use old text_alignment output files! I'll test it as soon as possible and close the issue then.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I'd like to follow up this issue.

**Comment by yinanazhou** [comment]
Hi @sabrina0822, I remember we have updated the MEI output to version 5 in rodan-staging last summer. Just want to double check that this change is on staging right now as @JoyfulGen mentioned that this change is not on rodan2.

**Comment by JoyfulGen** [comment]
@yinanazhou @sabrina0822 I'm a bit lost on where we're at, I'm so sorry! I know that, at the moment, files I have from e2e OMR in rodan2 have no divLines in syllables, ever. If I remember correctly, this was a request I made for a temporary-ish fix, because so few divLines actually have to be inserted into syllables that it took less time for me to do it manually. Is this still the case? Or are there changes in rodan_staging?

**Comment by sabrina0822** [comment]
@yinanazhou Sorry I just saw the question you asked a month back, the MEI encoding job should have been version 5 since some time last summer on both staging and production. 

@JoyfulGen I believe divlines, neumes, accidentals, and clefs are currently allowed to be inside a syllable. Would you like this changed to not let divlines be in the MEI output?

**Comment by JoyfulGen** [comment]
> 
> @JoyfulGen I believe divlines, neumes, accidentals, and clefs are currently allowed to be inside a syllable. Would you like this changed to not let divlines be in the MEI output?

I haven't processed any new folios in a while. I'd like to do a few and see how they look before I can answer! Is that ok?
