### ISSUE TITLE
Toggled syllable notification doesn't match MEI file

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#886]
When opening Einsie folio 247v, I get the notification that there's "No @precedes value for toggle-linked syllable: null." But when I do a word search in the MEI file, there's no syllable "null" anywhere.  

<img width="1440" alt="Toggled syllable  null" src="https://user-images.githubusercontent.com/83373378/174629752-0dbe4c3a-7bff-49db-af4c-958927180d07.png">

[247v_where_is_null.mei.zip](https://github.com/DDMAL/Neon/files/8941673/247v_where_is_null.mei.zip) 
 
As for "ta," that syllable does exists, but it doesn't have an @precedes value.

**Comment by JoyfulGen** [comment]
Ohhh, that makes sense! Sorry for missing that.

**Comment by jinh0** [comment]
The issue is with the MEI encoding job, because syllables (orange and pink) exist within the toggle-linked syllable (blue).

![Screen Shot 2022-06-23 at 4 37 57 PM](https://user-images.githubusercontent.com/40512164/175395198-16f76620-3f17-4bb0-b776-4506209cda63.png)

But there are still faulty / incorrect error notifications about toggled syllables, for instance, an error can occur if the @follows part of a toggle-linked syllable is deleted, then our algorithm will think that the spatially next syllable is part of the toggle-linked syllable, and thus produce an inaccurate error:

![Screen Shot 2022-06-23 at 4 39 51 PM](https://user-images.githubusercontent.com/40512164/175395519-764c0564-a089-49e8-aaf6-69974421a72c.png)

My pull request #900 fixes both issues by specifically searching for the syllable given by the @precedes/@follows ID instead of using a sorted array.

**Comment by yinanazhou** [comment]
Currently, Neon only checks adjacent syllables for @precedes/@follows. This kind of toggle-linked syllable (1, on the same staff; 2, have syllables in between) cannot be created in Neon though. This should be created in the MEI-encoding job (need @sabrina0822's confirmation). The key to the checking algorithm would be, whether toggle-linked syllables like this one happens in Neon. Need help from @JoyfulGen and @annamorphism to answer this question. 

I agree that the notification should be about the existing syllable. But remember that the user cannot delete part of a toggle-linked syllable in Neon because the two syllables are bonded. If the user deletes all the neumes in one of the toggle-linked syllables, the other syllable would be unlinked.

**Comment by annamorphism** [comment]
@JoyfulGen this seems to be a problem with the error message. the syllable *is* linked, so it doesn't have a <syl> marker at all, but that means it's pretty hard to tell the user what it is by referring to the text (it's the syllable starting the third staff, linked to the "ta" above.)  Not sure if there is a good solution for that.
As @jinh0 already pointed out, the problem is these weird intervening syllables, which (as @yinanazhou says) can't be made in Neon (nor would you want them to)--they've presumably come out of the MEI-encoding job. 
Searching for the ID directly instead of only looking at adjacent syllables would mean you could find that the two relevant syllables are, in fact, linked (correctly!)--there's not anything *missing*, which is what the error message seems to suggest. But it doesn't tell us that we have a bizarre syllable-inside-a-syllable situation, which is what is causing the problem in the first place, and is really what needs correcting.

**Comment by sabrina0822** [comment]
@JoyfulGen Was this made with the old MEI encoding job or the new one? This shouldn't happen so I might try using the TA and PF files to see if this still happens.

**Comment by yinanazhou** [comment]
> @JoyfulGen this seems to be a problem with the error message. the syllable _is_ linked, so it doesn't have a marker at all, but that means it's pretty hard to tell the user what it is by referring to the text (it's the syllable starting the third staff, linked to the "ta" above.) Not sure if there is a good solution for that. As @jinh0 already pointed out, the problem is these weird intervening syllables, which (as @yinanazhou says) can't be made in Neon (nor would you want them to)--they've presumably come out of the MEI-encoding job. Searching for the ID directly instead of only looking at adjacent syllables would mean you could find that the two relevant syllables are, in fact, linked (correctly!)--there's not anything _missing_, which is what the error message seems to suggest. But it doesn't tell us that we have a bizarre syllable-inside-a-syllable situation, which is what is causing the problem in the first place, and is really what needs correcting.


@jinh0, in this case, we should use Array.find() to find whether there is a corresponding syllable, check whether the following syllable index equals the preceding syllable plus one, and give different notifications on these two checks.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I have pushed the changes that fix the notifications for toggle-lined syllable check.

**Comment by JoyfulGen** [comment]
This looks great, thank you! Closing the issue now.
